# Generated by Django 4.1.5 on 2023-01-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Description'),
        ),
    ]
