# Generated by Django 4.1.5 on 2023-01-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('Private and Luxury', 'Private and Luxury'), ('Full-day Tours', 'Full-day Tours'), ('Day trips', 'Day trips'), ('Forest', 'Forest'), ('Favorites', 'Favorites')], max_length=50, verbose_name='Place Type'),
        ),
    ]
